# settings.yaml
# box_name: "sloopstash/ubuntu-22-04"
#box_name: "bento/ubuntu-22.04"
box_name: "generic/debian12"
# box_version: "2.1.1"
vm:
- name: kmaster1
  ip: 172.16.16.101
  memory: 2048
  cpus: 2
  vcpus: "0-1"
- name: kmaster2
  ip: 172.16.16.102
  memory: 2048
  cpus: 2
  vcpus: "2-3"
- name: kmaster3
  ip: 172.16.16.103
  memory: 2048
  cpus: 2
  vcpus: "4-5"
- name: kloadbalancer1
  ip: 172.16.16.51
  memory: 2048
  cpu: 2
  vcpus: "6-7"
- name: kloadbalancer2
  ip: 172.16.16.52
  memory: 2048
  cpu: 2
  vcpus: "8-9"
- name: kslave1
  ip: 172.16.16.201
  memory: 2048
  cpu: 2
  vcpus: "10-11"
- name: kslave2
  ip: 172.16.16.202
  memory: 2048
  cpu: 2
  vcpus: "12-13"
- name: kslave3
  ip: 172.16.16.203
  memory: 2048
  cpu: 2
  vcpus: "14-15"
