apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  labels:
    name: prometheus-conf
  namespace: observer
data:
  prometheus.yml: |-
    global:
      scrape_interval: 1s
    scrape_configs:
    - job_name: opentelemetrycollector-gateway
      static_configs:
        - targets:
          - opentelemetrycollector.observer.svc.cluster.local:8888
          - opentelemetrycollector.observer.svc.cluster.local:8889
