apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: agent-opentelemetry-collector
    app.kubernetes.io/name: opentelemetry-collector
  name: agent-opentelemetry-collector
rules:
- apiGroups:
  - ""
  resources:
    - pods
    - nodes
    - nodes/stats
    - nodes/proxy
    - namespaces
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - ""
  resources:
    - nodes/stats
    - nodes/proxy
  verbs:
  - get
- apiGroups:
  - "apps"
  resources:
    - replicasets
    - daemonsets
  verbs:
    - get
    - list
    - watch
- apiGroups:
  - extensions
  resources:
    - replicasets
    - daemonsets
  verbs:
    - get
    - list
    - watch
