apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: gateway-opentelemetry-collector
    app.kubernetes.io/name: opentelemetry-collector
    component: standalone-collector
  name: gateway-opentelemetry-collector
  namespace: default
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: gateway-opentelemetry-collector
    app.kubernetes.io/name: opentelemetry-collector
    component: standalone-collector
  ports:
  - appProtocol: grpc
    name: otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: prometheus
    port: 8889
    protocol: TCP
    targetPort: 8889
