apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: gateway-opentelemetry-collector
    app.kubernetes.io/name: opentelemetry-collector
  name: gateway-opentelemetry-collector
  namespace: default