Vagrant.configure(2) do |config|
  config.vm.box = "generic/debian12"

  config.vm.provider "qemu" do |qe|
    qe.arch = "x86_64"
    qe.machine = "q35"
    qe.cpu = "qemu64"
    qe.net_device = "virtio-net-pci"
    qe.ssh_port = "20022"
  end
end
