apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: proactivemonitoring.silentmode.com
spec:
  api:
    loadBalancer:
      class: Network
      type: Public
  authorization:
    rbac: {}
  awsLoadBalancerController:
    enabled: true
  certManager:
    enabled: true
  channel: stable
  cloudLabels:
    silentmode:environment: ronpos-staging
    silentmode:owner: engineering
    silentmode:service: proactive-monitoring
  cloudProvider: aws
  configBase: s3://proactive-monitoring-state/proactivemonitoring.silentmode.com
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-ap-southeast-1a-1
      name: a-1
    - encryptedVolume: true
      instanceGroup: control-plane-ap-southeast-1b-1
      name: b-1
    - encryptedVolume: true
      instanceGroup: control-plane-ap-southeast-1a-2
      name: a-2
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: control-plane-ap-southeast-1a-1
      name: a-1
    - encryptedVolume: true
      instanceGroup: control-plane-ap-southeast-1b-1
      name: b-1
    - encryptedVolume: true
      instanceGroup: control-plane-ap-southeast-1a-2
      name: a-2
    manager:
      backupRetentionDays: 90
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true
    legacy: false
  kubeProxy:
    enabled: false
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 0.0.0.0/0
  - ::/0
  kubernetesVersion: 1.29.6
  networkCIDR: 172.20.0.0/16
  networking:
    cilium:
      enableNodePort: true
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  - ::/0
  subnets:
  - cidr: 172.20.0.0/17
    name: ap-southeast-1a
    type: Public
    zone: ap-southeast-1a
  - cidr: 172.20.128.0/17
    name: ap-southeast-1b
    type: Public
    zone: ap-southeast-1b
  topology:
    dns:
      type: None

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: proactivemonitoring.silentmode.com
  name: control-plane-ap-southeast-1a-1
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20240607
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - ap-southeast-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: proactivemonitoring.silentmode.com
  name: control-plane-ap-southeast-1a-2
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20240607
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - ap-southeast-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: proactivemonitoring.silentmode.com
  name: control-plane-ap-southeast-1b-1
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20240607
  machineType: t2.medium
  maxSize: 1
  minSize: 1
  role: Master
  subnets:
  - ap-southeast-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: proactivemonitoring.silentmode.com
  name: nodes-ap-southeast-1a
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20240607
  machineType: t2.medium
  maxSize: 5
  minSize: 5
  role: Node
  subnets:
  - ap-southeast-1a
