- name: Initialize k8s cluster
  hosts: masters
  become: yes
  gather_facts: yes
  tasks:
    - name: Initialize kubeadm
      #ansible.builtin.shell: kubeadm init --control-plane-endpoint=172.16.16.100:6443 --apiserver-advertise-address={{ ansible_ssh_host }} --pod-network-cidr=192.168.0.0/16 --v=5
      ansible.builtin.shell: kubeadm init --apiserver-advertise-address={{ ansible_ssh_host }} --pod-network-cidr=192.168.0.0/16 --v=5
    
    - name: Create .kube config directory
      become: yes
      become_user: "{{ ansible_user }}"
      ansible.builtin.file:
        path: "$HOME/.kube"
        state: directory
        mode: "0755"

    - name: Install overlay network
      become: yes
      become_user: "{{ ansible_user }}"
      ansible.builtin.shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      run_once: true
      ignore_errors: true

    # - name: Copy admin.conf to user's kube config
    #   become: yes
    #   ansible.builtin.copy:
    #     src: /etc/kubernetes/admin.conf
    #     dest: $HOME/.kube/config
    #     remote_src: yes
    #     owner: "{{ ansible_user }}"

    - name: Save config to localhost
      ansible.builtin.fetch:
        src: /etc/kubernetes/admin.conf
        dest: /tmp/kubernetes/
        flat: yes
        fail_on_missing: true

    - name: Move kube config to local directory
      local_action:
        module: ansible.builtin.command
        args:
          cmd: "mv /tmp/kubernetes/admin.conf {{ lookup('env', 'HOME') }}/.kube/config"

    - name: Create join command
      ansible.builtin.shell: kubeadm token create --print-join-command
      register: join_command_output

    - name: Set join command output
      ansible.builtin.set_fact:
        join_command: "{{ join_command_output.stdout_lines[0] }}"

    - name: test join command output
      ansible.builtin.debug:
        msg:
          - "{{ join_command }}"

    - name: save fact to a file
      become_user: root
      ansible.builtin.copy:
        content: "{{ join_command }}"
        dest: "./join_command.txt"
        follow: yes
      delegate_to: localhost

- name: Link k8s cluster
  hosts: controlplanes:loadbalancers:slaves
  become: yes
  tasks:

    - name: fetch join command from the file
      ansible.builtin.slurp:
        src: "./join_command.txt"
      delegate_to: localhost
      register: join_command

    - name: test hostvar data
      ansible.builtin.debug:
        msg:
          - "{{ join_command }}"

    - name: set command as fact
      set_fact: 
        command: "{{ join_command.content | b64decode }}"

    - name: Join nodes to cluster
      ansible.builtin.shell: "{{ command }}"
