- name: Clear known hosts entries
  hosts: localhost
  gather_facts: false
  become: yes
  tasks:

    - name: gather list of all hosts
      ansible.builtin.set_fact:
        all_hosts: "{{ groups['all'] }}"

    - name: host check
      ansible.builtin.debug:
        msg: "Host: {{ hostvars[item].ansible_host }}"
      loop: "{{ all_hosts }}"

    - name: remove each host from known_hosts
      ansible.builtin.shell: "ssh-keygen -R {{ ansible_host }}"
      loop: "{{ all_hosts }}"
      ignore_errors: true

