# settings.yaml
box_name: "generic/debian12"
vm:
- name: kmaster1
  ip: 172.16.16.101
  memory: 2048
  cpus: 2
- name: kslave1
  ip: 172.16.16.201
  memory: 2048
  cpu: 2
- name: kslave2
  ip: 172.16.16.202
  memory: 2048
  cpu: 2
- name: kloadbalancer1
  ip: 172.16.16.51
  memory: 2048
  cpu: 2
