ENV['VAGRANT_NO_PARALLEL'] = 'yes'
require 'yaml'
settings = YAML.load_file(File.join(File.dirname(__FILE__), 'settings.yaml'))

Vagrant.configure("2") do |config|
  config.vm.box = settings['box_name']
  # config.vm.box_version = settings['box_version']
  config.vm.box_check_update = false

  settings['vm'].each_with_index do |vm_config, index|

    config.vm.define vm_config['name'] do |vm|
      vm.vm.hostname = vm_config['name']
      vm.vm.network "private_network", ip: vm_config['ip']
      vm.vm.synced_folder ".", "/vagrant", disabled: false
      vm.vm.provider "libvirt" do |vb|
        
        vb.username = vm_config['name']
        vb.password = "silentmode"
        
        vb.memory = vm_config['memory']
        # vb.cpus = vm_config['cpus']
        
        # vb.numa_nodes = [
        # 	{:cpus => vm_config['vcpus'], :memory => vm_config['memory']}
        # ]
      end

      # vm.vm.provision "shell", inline: <<-SHELL
      #   apt update
      #   apt upgrade -y
      #   apt install -y wget vim net-tools gcc make tar git unzip sysstat tree
      # SHELL

      vm.vm.provision :ansible do |ansible|
        ansible.verbose = "vv"
        ansible.playbook = "bootstrap.yaml"
      end

      vm.vm.provision :ansible do |ansible|
        ansible.verbose = "vv"
        ansible.playbook = "initial.yaml"
      end

      vm.vm.provision :ansible do |ansible|
        ansible.verbose = "vv"
        ansible.playbook = "dependencies.yaml"
      end

    end
  end
end
