receivers:
  otlp:
    protocols:
      grpc:
      http:
  hostmetrics:
    root_path: /hostfs
    collection_interval: 1s
    scrapers:
      cpu:
      load:
      memory:
      disk:
      filesystem:
      network:

exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  otlp/gateway:
    endpoint: 192.168.0.120:32001
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889
  
processors:
  batch:
  resourcedetection/docker:
    detectors:
      - env
      - docker
    override: true
  attributes/station:
    actions:
      - key: station.code
        value: ${STATION_CODE}
        action: insert
      - key: host.name
        value: ${HOST_NAME}
        action: upsert
  memory_limiter:
    check_interval: 1s
    limit_percentage: 50
    spike_limit_percentage: 30

extensions:
  memory_ballast:
    size_in_percentage: 20
  
service:
  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - memory_limiter
        - resourcedetection/docker
        - attributes/station
      exporters:
        - otlp/gateway
    metrics:
      receivers:
        - otlp
        - hostmetrics
      processors:
        - memory_limiter
        - resourcedetection/docker
        - attributes/station
      exporters:
        - prometheus
        - otlp/gateway
