apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '3000'
spec:
  selector:
    app: grafana
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
