apiVersion: v1
kind: Service
metadata:
  name: otel-agent-headless-service
  labels:
    app: otel-agent
spec:
  clusterIP: None
  selector:
    app: otel-agent
  ports:
  - name: otlp
    port: 4317
    targetPort: 4317

---

apiVersion: v1
kind: Service
metadata:
  name: opentelemetry-collector-lb
  labels:
    app: otel-agent
spec:
  type: ClusterIP
  selector:
    app: otel-agent
  ports:
  - name: otlp
    port: 4317
    targetPort: 4317