apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  labels:
    name: prometheus-conf
data:
  prometheus.yml: |-
    global:
      scrape_interval: 1s
    scrape_configs:
    - job_name: opentelemetrycollector-gateway
      static_configs:
        - targets:
          # - otel-collector.default.svc.cluster.local:8888
          # - otel-collector.default.svc.cluster.local:8889
          # - opentelemetry-collector-lb.default.svc.cluster.local:8888
          # - opentelemetry-collector-lb.default.svc.cluster.local:8889
          - deployment-collector-dev-opentelemetry-collector.default.svc.cluster.local:8888
