apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opensearch
  labels:
    app: opensearch
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opensearch
subjects:
  - kind: ServiceAccount
    name: opensearch
    namespace: default
