- name: Apt Update
  hosts: all
  become: true
  tasks:
    - name: Install apt-transport-https and curl
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - curl
          - gpg
        state: present
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
 

- name: Containerd installation
  hosts: all
  become: true
  tasks:
    - name: Removing conflicting Docker-related packages
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-doc
          - docker-compose
          - podman-docker
          - containerd
          - runc
        state: absent
    
    - name: Install prerequisites
      ansible.builtin.apt:
        name: ca-certificates
        state: present

    - name: Create /etc/apt/keyrings directory
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"
    
    - name: Get Docker's official GPG key
      ansible.builtin.uri:
        url: https://download.docker.com/linux/debian/gpg
        method: GET
        dest: /etc/apt/keyrings/docker.asc
        follow_redirects: safe

    - name: Modify key permission
      ansible.builtin.file:
        path: /etc/apt/keyrings/docker.asc
        mode: 'a+r'
    
    - name: Get system architecture
      ansible.builtin.command: dpkg --print-architecture
      register: architecture_output
    
    - name: Get OS version codename
      become: true
      ansible.builtin.shell: /etc/os-release && echo "$VERSION_CODENAME"
      register: version_codename
    
    - name: Add repository to Apt sources
      ansible.builtin.apt_repository:
        repo: |
          deb [arch={{ architecture_output.stdout }}
          signed-by=/etc/apt/keyrings/docker.asc] 
          https://download.docker.com/linux/debian
          {{ version_codename.stdout }} stable
        filename: docker.list
        state: present
      
    - name: Verify file repository exist
      ansible.builtin.stat:
        path: /etc/apt/sources.list.d/docker.list
        register: filestat

    - name: Validate file existence
      ansible.builtin.assert:
        that: filestat.stat.exists
        fail_msg: |
          Docker repository does not exist at 
          /etc/apt/sources.list.d/docker.list

    ### alternative
    # - name: Add Docker's official GPG key
    #   apt_key:
    #     url: https://download.docker.com/linux/ubuntu/gpg
    #     state: present

    # - name: Add Docker repository
    #   apt_repository:
    #     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    #     state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker and related packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Verify Docker installation
      community.docker.docker_container:
        name: hello-world
        image: hello-world
        state: started

- name: Containerd configuration
  hosts: all
  become: true
  tasks:
    - name: Create the /etc/containerd/directory
      file:
        path: /etc/containerd
        state: directory
        mode: "0755"

    - name: Retrieve default containerd configuration
      ansible.builtin.command: containerd config default
      register: containerd_config

    - name: Write containerd configuration to file
      ansible.builtin.copy:
        content: containerd_config.stdout
        dest: /etc/containerd/config.toml

    - name: Set SystemCgroup option to true
      ansible.builtin.lineinfile:
        path: /etc/containerd/config.toml
        regexp: '^SystemdCgroup\s*='
        line: "SystemdCgroup = true"
        state: present

- name: k8s installation
  hosts: all
  become: true
  tasks:
    - name: Add k8s apt key
      ansible.builtin.get_url:
        url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
        dest: /tmp/Release.key

    - name: Dearmor GPG key
      ansible.builtin.shell: |
        gpg --dearmor /tmp/Release.key 
        -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add k8s repository
      ansible.builtin.apt_repository:
        repo: |
          deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] 
          https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /
        state: present

    - name: Verify file repository exist
      ansible.builtin.stat:
        path: /etc/apt/sources.list.d/kubernetes.list
        register: filestat

    - name: Validate file existence
      ansible.builtin.assert:
        that: filestat.stat.exists
        fail_msg: |
          k8s repository does not exist at 
          /etc/apt/sources.list.d/kubernetes.list

    - name: Update package cache
      ansible.builtin.apt:
        update_cache: yes

    - name: k8s packages installation
      ansible.builtin.apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
          - kubernetes-cni
