- name: Add user as sudoer via visudo
  hosts: all
  become: true
  tasks:
    - name: Grant sudo priveleges to the new user using visudo
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        line: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"

- name: Disable swap memory
  hosts: all
  become: true
  tasks:
    - name: Command disable
      ansible.builtin.command: swapoff -a

    - name: File disable
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '#\ 1'
