Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.network "private_network", ip: "192.168.10.10", auto_config: false
  config.vm.provider "virtualbox" do |qe|
    # qe.arch = "x86_64"
    # qe.machine = "q35"
    qe.cpus = "2"
    qe.memory = 1024
    # qe.net_device = "virtio-net-pci"
  end
end
