apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: daemonset-collector-dev
    app.kubernetes.io/name: opentelemetry-collector
  name: daemonset-collector-dev-opentelemetry-collector
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/stats
  - nodes/proxy
  verbs:
  - get