apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "1"
    meta.helm.sh/release-name: daemonset-collector-dev
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-07-03T21:31:24Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: daemonset-collector-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/version: 0.103.1
    helm.sh/chart: opentelemetry-collector-0.96.0
  name: daemonset-collector-dev-opentelemetry-collector-agent
  namespace: default
  resourceVersion: "1040"
  uid: 5bd681f0-d187-44bd-8f54-8e185baeb985
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: daemonset-collector-dev
      app.kubernetes.io/name: opentelemetry-collector
      component: agent-collector
  template:
    metadata:
      annotations:
        checksum/config: e476810b2c84d2dd54659c526a558164477ecceb00b5f9a77eff882b80fa9856
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: daemonset-collector-dev
        app.kubernetes.io/name: opentelemetry-collector
        component: agent-collector
    spec:
      containers:
      - args:
        - --config=/conf/relay.yaml
        command:
        - /otelcontribcol
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: otelcontribcol-dev:0.0.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 13133
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: opentelemetry-collector
        ports:
        - containerPort: 6831
          hostPort: 6831
          name: jaeger-compact
          protocol: UDP
        - containerPort: 14250
          hostPort: 14250
          name: jaeger-grpc
          protocol: TCP
        - containerPort: 14268
          hostPort: 14268
          name: jaeger-thrift
          protocol: TCP
        - containerPort: 4317
          hostPort: 4317
          name: otlp
          protocol: TCP
        - containerPort: 4318
          hostPort: 4318
          name: otlp-http
          protocol: TCP
        - containerPort: 9411
          hostPort: 9411
          name: zipkin
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 13133
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /conf
          name: opentelemetry-collector-configmap
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: daemonset-collector-dev-opentelemetry-collector
      serviceAccountName: daemonset-collector-dev-opentelemetry-collector
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: relay
            path: relay.yaml
          name: daemonset-collector-dev-opentelemetry-collector-agent
        name: opentelemetry-collector-configmap
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 5
  desiredNumberScheduled: 5
  numberMisscheduled: 0
  numberReady: 0
  numberUnavailable: 5
  observedGeneration: 1
  updatedNumberScheduled: 5