apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: deployment-collector-dev
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-07-03T21:31:31Z"
  labels:
    app.kubernetes.io/instance: deployment-collector-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/version: 0.103.1
    component: standalone-collector
    helm.sh/chart: opentelemetry-collector-0.96.0
  name: deployment-collector-dev-opentelemetry-collector
  namespace: default
  resourceVersion: "1093"
  uid: 76e31ef6-1c56-4485-bd05-b26eb5a9cec0
spec:
  clusterIP: 10.96.22.135
  clusterIPs:
  - 10.96.22.135
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: jaeger-compact
    port: 6831
    protocol: UDP
    targetPort: 6831
  - name: jaeger-grpc
    port: 14250
    protocol: TCP
    targetPort: 14250
  - name: jaeger-thrift
    port: 14268
    protocol: TCP
    targetPort: 14268
  - appProtocol: grpc
    name: otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  - name: zipkin
    port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    app.kubernetes.io/instance: deployment-collector-dev
    app.kubernetes.io/name: opentelemetry-collector
    component: standalone-collector
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}