apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: daemonset-collector-dev
    app.kubernetes.io/name: opentelemetry-collector
  name: daemonset-collector-dev-opentelemetry-collector
  namespace: default