apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: daemonset-collector-dev
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-07-03T21:31:24Z"
  labels:
    app.kubernetes.io/instance: daemonset-collector-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: opentelemetry-collector
    app.kubernetes.io/version: 0.103.1
    helm.sh/chart: opentelemetry-collector-0.96.0
  name: daemonset-collector-dev-opentelemetry-collector
  namespace: default
  resourceVersion: "1010"
  uid: 4a28a829-e602-4778-bff1-ab98515c1a74