apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate
spec:
  secretName: proactivemonitoring
  dnsNames:
    - dashboard.monitoring.staging.ronpos.com
    - prometheus.monitoring.staging.ronpos.com
    - otlpv2.monitoring.staging.ronpos.com
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
