apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: data-prepper
    app.kubernetes.io/name: data-prepper
  name: data-prepper-config
  namespace: default
data:
  pipelines.yaml: |
    metrics-pipeline:
      source:
        otel_metrics_source:
          ssl: false
          port: 21891
      processor:
        - otel_metrics:
      sink:
        - stdout:
        - opensearch:
            hosts: ["https://opensearch-cluster-master:9200"]
            insecure: true
            username: admin
            password: zmgf-x19a/M2
            index: otlp_metrics
    logs-pipeline:
      source:
        otel_logs_source:
          ssl: false
          port: 21892
      processor:
        - grok:
            match:
              log:
                - "%{SYSLOGTIMESTAMP:timestamp} %{HOSTNAME:hostname} %{PROG:program}\\[%{NUMBER:pid}\\]: %{GREEDYDATA:message}"
      sink:
        - stdout:
        - opensearch:
            hosts: ["https://opensearch-cluster-master:9200"]
            insecure: true
            username: admin
            password: zmgf-x19a/M2
            index: otlp_logs
    otel-trace-pipeline:
      workers: 2
      source:
        otel_trace_source:
          ssl: false
      buffer:
        bounded_blocking:
          buffer_size: 10240
          batch_size: 160
      sink:
        - pipeline:
            name: raw-pipeline
        - pipeline:
            name: service-map-pipeline
    raw-pipeline:
      workers: 2
      source:
        pipeline:
          name: otel-trace-pipeline
      buffer:
        bounded_blocking:
          buffer_size: 10240
          batch_size: 160
      processor:
        - otel_traces: null
        - otel_trace_group:
            hosts:
              - https://opensearch-cluster-master:9200
            insecure: true
            username: admin
            password: zmgf-x19a/M2
      sink:
        - opensearch:
            hosts:
              - https://opensearch-cluster-master:9200
            index_type: trace-analytics-raw
            insecure: true
            username: admin
            password: zmgf-x19a/M2
    service-map-pipeline:
      delay: "100"
      source:
        pipeline:
          name: otel-trace-pipeline
      buffer:
        bounded_blocking:
          buffer_size: 10240
          batch_size: 160
      processor:
        - service_map_stateful:
      sink:
        - opensearch:
            hosts:
              - https://opensearch-cluster-master:9200
            index_type: trace-analytics-service-map
            insecure: true
            username: admin
            password: zmgf-x19a/M2
  data-prepper-config.yaml: |
    ssl: false
    # peer_forwarder:
    #   discovery_mode: "dns"
    #   domain_name: "data-prepper-headless"
    #   ssl: false

