apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: data-prepper
    app.kubernetes.io/name: data-prepper
  name: data-prepper-headless
  namespace: default
spec:
  clusterIP: None
  ports:
    - name: otel-source-trace
      port: 21890
      targetPort: 21890
    - name: otel-source-metrics
      port: 21891
      targetPort: 21891
    - name: otel-source-logs
      port: 21892
      targetPort: 21892
  selector:
    app.kubernetes.io/instance: data-prepper
    app.kuberentes.io/name: data-prepper
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-prepper
  name: data-prepper-metrics
spec:
  type: ClusterIP
  ports:
    - name: core-api
      port: 4900
      targetPort: 4900
  selector:
    app: data-prepper
status:
  loadBalancer: {}
