apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: data-prepper
    app.kubernetes.io/name: data-prepper
  name: data-prepper
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: data-prepper
      app.kubernetes.io/name: data-prepper
      nodeType: misc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: data-prepper
        app.kubernetes.io/name: data-prepper
        nodeType: misc
    spec:
      containers:
        - image: opensearchproject/data-prepper:latest
          name: data-prepper
          imagePullPolicy: IfNotPresent
          ports:
            - name: core-api
              containerPort: 4900
            - name: traces
              containerPort: 21890
            - name: metrics
              containerPort: 21891
            - name: logs
              containerPort: 21892
          resources: {}
          volumeMounts:
            - name: data-prepper-config
              mountPath: /usr/share/data-prepper/pipelines/pipelines.yaml
              subPath: pipelines.yaml
            - name: data-prepper-config
              mountPath: /usr/share/data-prepper/config/data-prepper-config.yaml
              subPath: data-prepper-config.yaml
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: data-prepper-config
          configMap:
            name: data-prepper-config
