apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: data-prepper
    app.kubernetes.io/name: data-prepper
  name: data-prepper-config
  namespace: default
data:
  pipelines.yaml: |
    entry-pipeline:
      delay: "100"
      source:
        otel_trace_source:
          health_check_service: true
          ssl: false
      sink:
        - pipeline:
            name: "raw-pipeline"
        - pipeline:
            name: "service-map-pipeline"
    raw-pipeline:
      source:
        pipeline:
          name: "entry-pipeline"
      processor:
        - otel_traces:
      sink:
        - stdout:
    service-map-pipeline:
      delay: "100"
      source:
        pipeline:
          name: "entry-pipeline"
      processor:
        - service_map_stateful:
      sink:
        - stdout:
  data-prepper-config.yaml: |
    ssl: false
    # peer_forwarder:
    #   discovery_mode: "dns"
    #   domain_name: "data-prepper-headless"
    #   ssl: false

