clusterName: opensearch-cluster

nodeGroup: data

masterService: opensearch-cluster-master

roles:
  - data

replicas: 3

extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: zmgf/a-262PD-p

persistence:
  enabled: false

majorVersion: 2.16.0

config:
  opensearch.yml: |
    plugins:
      query:
        datasources:
          encryption:
            masterkey: wKLP9vHwPsNx7SI3NX5JEhmg

nodeSelector:
  node: cluster-opensearch
