clusterName: opensearch-cluster

nodeGroup: data

masterService: opensearch-cluster-master

roles:
  - data

replicas: 3

extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: opensearch-admin-password
        key: password

opensearchJavaOpts: "-Xmx2g -Xms2g"

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "1"
    memory: "2.5Gi"

persistence:
  enabled: true
  size: 600Gi

majorVersion: 2.17.0

config:
  opensearch.yml: |
    plugins:
      query:
        datasources:
          encryption:
            masterkey: wKLP9vHwPsNx7SI3NX5JEhmg
    http:
      host: 0.0.0.0
      port: 9200
      cors:
        allow-origin: "*"
        enabled: true
        allow-methods: OPTIONS,HEAD,GET,POST,PUT,DELETE
        allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length

envFrom:
  - secretRef:
      name: opensearch-admin-password

# secretMounts:
#   - name: opensearch-certs-node
#     secretName: opensearch-certs
#     path: /usr/share/opensearch/config/node1.pem
#     subPath: node1.pem
#   - name: opensearch-certs-node-key
#     secretName: opensearch-certs
#     path: /usr/share/opensearch/config/node1-key.pem
#     subPath: node1-key.pem
#   - name: opensearch-certs-root-ca
#     secretName: opensearch-certs
#     path: /usr/share/opensearch/config/root-ca.pem
#     subPath: root-ca.pem
#   - name: opensearch-certs-admin-crt
#     secretName: opensearch-certs
#     path: /usr/share/opensearch/config/admin-crt.pem
#     subPath: admin-crt.pem
#   - name: opensearch-certs-admin-key
#     secretName: opensearch-certs
#     path: /usr/share/opensearch/config/admin-key.pem
#     subPath: admin-key.pem