extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: zmgf-x19a/M2

persistence:
  enabled: false

majorVersion: 2.16.0

config:
  opensearch.yml: |
    plugins:
      query:
        datasources:
          encryption:
            masterkey: wKLP9vHwPsNx7SI3NX5JEhmg
    http:
      host: 0.0.0.0
      port: 9200
      cors:
        allow-origin: "*"
        enabled: true
        allow-methods: OPTIONS,HEAD,GET,POST,PUT,DELETE
        allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length