clusterName: opensearch-cluster

nodeGroup: master

masterService: opensearch-cluster-master

roles:
  - master

replicas: 1

extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: zmgf/a-262PD-p

persistence:
  enabled: false

majorVersion: 2.16.0

config:
  opensearch.yml: |
    plugins:
      query:
        datasources:
          encryption:
            masterkey: wKLP9vHwPsNx7SI3NX5JEhmg
    http.host:0.0.0.0
    http.port:9200
    http.cors.allow-origin:"http://localhost"
    http.cors.enabled:true
    http.cors.allow-headers:X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
    http.cors.allow-credentials:true

nodeSelector:
  node: cluster-default
