clusterName: opensearch-cluster

nodeGroup: master

masterService: opensearch-cluster-master

roles:
  - master
  - data
  - ingest
  - remote_cluster_client

replicas: 3

extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: opensearch-admin-password
        key: password

persistence:
  enabled: true
  
majorVersion: 2.17.0

config:
  opensearch.yml: |
    plugins:
      query:
        datasources:
          encryption:
            masterkey: wKLP9vHwPsNx7SI3NX5JEhmg
     
    http:
      host: 0.0.0.0
      port: 9200
      cors:
        allow-origin: "*"
        enabled: true
        allow-methods: OPTIONS,HEAD,GET,POST,PUT,DELETE
        allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length
 
# this is for placing the cluster on specific nodes
# nodeSelector:
#   node: cluster-opensearch

envFrom:
  - secretRef:
      name: opensearch-admin-password

keystore:
  - secretName: opensearch-smtp-email
  - secretName: opensearch-smtp-password

# secretMounts:
#   - name: opensearch-certs-node
#     secretName: opensearch-certs
#     path: /usr/share/opensearch/config/node1.pem
#     subPath: node1.pem
#   - name: opensearch-certs-node-key
#     secretName: opensearch-certs
#     path: /usr/share/opensearch/config/node1-key.pem
#     subPath: node1-key.pem
#   - name: opensearch-certs-root-ca
#     secretName: opensearch-certs
#     path: /usr/share/opensearch/config/root-ca.pem
#     subPath: root-ca.pem
#   - name: opensearch-certs-admin-crt
#     secretName: opensearch-certs
#     path: /usr/share/opensearch/config/admin.pem
#     subPath: admin.pem
#   - name: opensearch-certs-client
#     secretName: opensearch-certs
#     path: /usr/share/opensearch/config/client.pem
#     subPath: client.pem
#   - name: opensearch-certs-client-key
#     secretName: opensearch-certs
#     path: /usr/share/opensearch/config/client-key.pem
#     subPath: client-key.pem

opensearchJavaOpts: "-Xmx8g -Xms8g"

resources:
  requests:
    cpu: "500m"
    memory: "8Gi"

persistence:
  enabled: true
  size: 600Gi