clusterName: opensearch-cluster

nodeGroup: master

masterService: opensearch-cluster-master

roles:
  - master

replicas: 3

extraEnvs:
  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    value: zmgf/a-262PD-p

persistence:
  enabled: false

majorVersion: 2.17.0

config:
  opensearch.yml: |
    plugins:
      query:
        datasources:
          encryption:
            masterkey: wKLP9vHwPsNx7SI3NX5JEhmg
    
    # http.host:0.0.0.0
    # http.port:9200
    # http.cors.allow-origin:"*"
    # http.cors.enabled:true
    # http.cors.allow-headers:X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
    # http.cors.allow-credentials:true
    # http.cors.allow-methods: OPTIONS,HEAD,GET,POST,PUT,DELETE

# nodeSelector:
#   node: cluster-default

extraObjects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: notifications-core-email
    data:
      opensearch.notifications.core.email.monitoring.username: bW9uaXRvcmluZ0Bub3RpZmljYXRpb25zLmhvcy5zdGFnaW5nLnJvbnBvcy5jb20=
  - apiVersion: v1
    kind: Secret
    metadata:
      name: notifications-core-password
    data:
      opensearch.notifications.core.email.monitoring.password: ZjA2N2FiNjc3ODAwNWIzMzk0MThlY2FlMmNhZTJjMWMtMmI3NTVkZjgtNzcxMjA3YTk=

keystore:
  - secretName: notifications-core-email
  - secretName: notifications-core-password