apiVersion: v1
kind: Service
metadata:
  name: opentelemetrycollector
spec:
  selector:
    app.kubernetes.io/name: opentelemetrycollector
  type: ClusterIP
  ports:
  - name: prometheus
    port: 8889
    targetPort: 8889
    protocol: TCP
  - name: metrics
    port: 8888
---

apiVersion: v1
kind: Service
metadata:
  name: opentelemetrycollector-gateway
spec:
  selector:
    app.kubernetes.io/name: opentelemetrycollector
  type: ClusterIP
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
    protocol: TCP
  
