apiVersion: apps/v1
kind: Deployment
metadata:
  name: opentelemetrycollector
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetrycollector
  template:
    metadata:
      labels:
        app.kubernetes.io/name: opentelemetrycollector
    spec:
      serviceAccountName: opentelemetrycollector
      containers:
        - name: otelcol
          args:
          - --config=/conf/collector.yaml
          image: otel/opentelemetry-collector-contrib:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4317
          resources:
            limits:
              cpu: 100m
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 2Gi
          volumeMounts:
            - name: collector-config
              mountPath: /conf
              readOnly: true
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: hostfs
              mountPath: /hostfs
              readOnly: true
              mountPropagation: HostToContainer
      terminationGracePeriodSeconds: 30
      volumes:
      - name: collector-config
        configMap:
          items:
          - key: collector.yaml
            path: collector.yaml
          name: collector-config
      - name: varlog
        hostPath: 
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: hostfs
        hostPath:
          path: /

