apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  labels:
    name: prometheus-conf
data:
  prometheus.yml: |-
    global:
      scrape_interval: 1s
    scrape_configs:
    - job_name: opentelemetrycollector-gateway
      static_configs:
        - targets:
          - opentelemetrycollector.default.svc.cluster.local:8888
          - opentelemetrycollector.default.svc.cluster.local:8889
          - opentelemetry-collector-daemonset-agent-5txvn.default.svc.cluster.local:8888
          - opentelemetry-collector-daemonset-agent-5txvn.default.svc.cluster.local:8889

