receivers:
  otlp:
    protocols:
      grpc:
      http:
  syslog:
    tcp:
      listen_address: '0.0.0.0:54527'
    protocol: rfc3164
    location: UTC
    operators:
      - type: move
        from: attributes.message
        to: body
  filelog:
    include:
      - /var/log/system.log

exporters:
  prometheus:
    endpoint: 0.0.0.0:8889
  debug:
    verbosity: detailed
   
processors:
  batch:
  resourcedetection/docker:
    detectors:
      - env
      - docker
    override: true
  memory_limiter:
    check_interval: 1s
    limit_percentage: 50
    spike_limit_percentage: 30

extensions:
  memory_ballast:
    size_in_percentage: 20
  
service:
  telemetry:
    logs:
      encoding: json
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - debug
    metrics:
      receivers:
        - otlp
      exporters:
        - prometheus
        - debug
    logs:
      receivers:
        - filelog
      exporters:
        - debug
