apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: nginx-wrr
spec:
  weighted:
    services:
      - name: nginx-deploy-main
        port: 80
        weight: 1
      - name: nginx-deploy-blue
        port: 80
        weight: 1
      - name: nginx-deploy-green
        port: 80
        weight: 1
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`a58741bbf3ca54c6091e2defcfc510e4-1375db3c2aaddb50.elb.ap-southeast-1.amazonaws.com`)
    kind: Rule
    services:
    - name: nginx-wrr
      kind: TraefikService
