apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: data-prepper
    app.kubernetes.io/name: data-prepper
  name: data-prepper-config
  namespace: default
data:
  pipelines.yaml: |
    metrics-pipeline:
      workers: 4
      source:
        otel_metrics_source:
          ssl: false
          port: 21891
      buffer:
        bounded_blocking:
          buffer_size: 4096
          batch_size: 1024
      processor:
        - otel_metrics:
            calculate_histogram_buckets: true
            calculate_exponential_histogram_buckets: true
            exponential_histogram_max_allowed_scale: 10
            flatten_attributes: false
        - flatten:
            source: attributes
            target: ""
            remove_processed_fields: true
        - rename_keys:
            entries:
              - from_key: resource.attributes.position
                to_key: position
              - from_key: resource.attributes.site@name
                to_key: site-name
              - from_key: resource.attributes.city
                to_key: city
              - from_key: resource.attributes.region
                to_key: region
              - from_key: resource.attributes.postcode
                to_key: postcode
              - from_key: resource.attributes.state
                to_key: state
              - from_key: metric.attributes.sip@health
                to_key: sip-health
              - from_key: metric.attributes.capillary@health
                to_key: capillary-health
              - from_key: metric.attributes.ghl@health
                to_key: ghl-health
      sink:
        - stdout:
        - s3:
            aws:
              region: ap-southeast-1
            max_retries: 5
            bucket: proactive-monitoring-dataprepper
            object_key:
              path_prefix: metrics/%{yyyy}/%{MM}/%{dd}/
            threshold:
              event_count: 10000
              maximum_size: 50mb
              event_collect_timeout: 15s
            codec:
              json:
            buffer_type: in_memory
            compression: gzip
    metrics-pipeline-2:
      workers: 4
      source:
        s3:
          notification_type: sqs
          codec:
            json:
          compression: gzip
          sqs:
            queue_url: "https://sqs.ap-southeast-1.amazonaws.com/530830676072/dataprepper-metrics-queue"
          aws:
            region: ap-southeast-1
      sink:
        - opensearch:
            hosts: ["https://opensearch-cluster-master:9200"]
            insecure: true
            username: admin
            password: zmgf-x19a/M2
            index: otlp-metrics-%{yyyy-MM-dd-HH}-
    logs-pipeline:
      workers: 4
      source:
        otel_logs_source:
          ssl: false
          port: 21892
      buffer:
        bounded_blocking:
      processor:
        - grok:
            match:
              log:
                - "%{SYSLOGTIMESTAMP:timestamp} %{HOSTNAME:hostname} %{PROG:program}\\[%{NUMBER:pid}\\]: %{GREEDYDATA:message}"
      sink:
        - s3:
            aws:
              region: ap-southeast-1
            max_retries: 5
            bucket: proactive-monitoring-dataprepper
            object_key:
              path_prefix: logs/%{yyyy}/%{MM}/%{dd}/
            threshold:
              event_count: 1
              maximum_size: 50mb
              event_collect_timeout: 15s
            codec:
              json:
            buffer_type: in_memory
            compression: gzip
    logs-pipeline-2:
      workers: 4
      source:
        s3:
          notification_type: sqs
          codec:
            json:
          compression: gzip
          sqs:
            queue_url: https://sqs.ap-southeast-1.amazonaws.com/530830676072/dataprepper-logs-queue
          aws:
            region: ap-southeast-1
      sink:
        - stdout:
        - opensearch:
            hosts: ["https://opensearch-cluster-master:9200"]
            insecure: true
            username: admin
            password: zmgf-x19a/M2
            index: otlp-logs-%{yyyy-MM-dd-HH}-
    trace-pipeline:
      workers: 4
      source:
        otel_trace_source:
          ssl: false
      buffer:
        bounded_blocking:
          buffer_size: 10240
          batch_size: 160
      sink:
        - s3:
            aws:
              region: ap-southeast-1
            max_retries: 5
            bucket: proactive-monitoring-dataprepper
            object_key:
              path_prefix: traces/%{yyyy}/%{MM}/%{dd}/
            threshold:
              event_count: 1
              maximum_size: 50mb
              event_collect_timeout: 15s
            codec:
              json:
            buffer_type: in_memory
            compression: gzip
    trace-pipeline-2:
      workers: 4
      source:
        s3:
          notification_type: sqs
          codec:
            json:
          sqs:
            queue_url: https://sqs.ap-southeast-1.amazonaws.com/530830676072/dataprepper-trace-queue
          aws:
            region: ap-southeast-1
          compression: gzip
      sink:
        - pipeline:
            name: raw-pipeline
        - pipeline:
            name: service-map-pipeline
    raw-pipeline:
      workers: 4
      source:
        pipeline:
          name: trace-pipeline-2
      buffer:
        bounded_blocking:
          buffer_size: 10240
          batch_size: 160
      processor:
        - otel_traces: null
        - otel_trace_group:
            hosts:
              - https://opensearch-cluster-master:9200
            insecure: true
            username: admin
            password: zmgf-x19a/M2
      sink:
        - opensearch:
            hosts:
              - https://opensearch-cluster-master:9200
            index_type: trace-analytics-raw
            insecure: true
            username: admin
            password: zmgf-x19a/M2
    service-map-pipeline:
      workers: 4
      source:
        pipeline:
          name: trace-pipeline-2
      buffer:
        bounded_blocking:
          buffer_size: 10240
          batch_size: 160
      processor:
        - service_map_stateful:
      sink:
        - opensearch:
            hosts:
              - https://opensearch-cluster-master:9200
            index_type: trace-analytics-service-map
            insecure: true
            username: admin
            password: zmgf-x19a/M2
  data-prepper-config.yaml: |
    ssl: false
    circuit_breakers:
      heap:
        usage: 2gb
        reset: 30s
        check_interval: 5s
