apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: deployment-collector-dev
    app.kubernetes.io/name: opentelemetry-collector
    helm.sh/chart: opentelemetry-collector-0.96.0
  name: deployment-collector-dev-opentelemetry-collector
  namespace: default