apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: data-prepper
  name: data-prepper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: data-prepper
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.33.0 (HEAD)
      labels:
        io.kompose.network/poc-default: "true"
        io.kompose.service: data-prepper
    spec:
      containers:
        - image: opensearchproject/data-prepper:latest
          name: data-prepper
          ports:
            - containerPort: 21890
              hostPort: 21890
              protocol: TCP
            - containerPort: 21891
              hostPort: 21891
              protocol: TCP
            - containerPort: 21892
              hostPort: 21892
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/data-prepper/pipelines/pipelines.yaml
              name: data-prepper-cm0
              subPath: pipelines.yaml
            - mountPath: /usr/share/data-prepper/config/data-prepper-config.yaml
              name: data-prepper-cm1
              subPath: data-prepper-config.yaml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: pipelines.yaml
                path: pipelines.yaml
            name: data-prepper-cm0
          name: data-prepper-cm0
        - configMap:
            items:
              - key: data-prepper-config.yaml
                path: data-prepper-config.yaml
            name: data-prepper-cm1
          name: data-prepper-cm1
