apiVersion: v1
data:
  data-prepper-config.yaml: |
    ssl: false
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: data-prepper
  name: data-prepper-cm1
