apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.33.0 (HEAD)
  labels:
    io.kompose.service: data-prepper
  name: data-prepper
spec:
  ports:
    - name: "21890"
      port: 21890
      targetPort: 21890
    - name: "21891"
      port: 21891
      targetPort: 21891
    - name: "21892"
      port: 21892
      targetPort: 21892
  selector:
    io.kompose.service: data-prepper
