apiVersion: v1
data:
  pipelines.yaml: |+
    otel-trace-pipeline:
      source:
        otel_trace_source:
          ssl: false
          authentication:
            unauthenticated:
      buffer:
        bounded_blocking:
          buffer_size: 25600
          batch_size: 400
      sink:
        - pipeline:
            name: "raw-pipeline"
        - pipeline:
            name: "service-map-pipeline"

    raw-pipeline:
      source:
        pipeline:
          name: "otel-trace-pipeline"
      buffer:
        bounded_blocking:
          buffer_size: 25600
          batch_size: 3200
      processor:
        - otel_traces:
        - otel_trace_group:
            hosts: ["https://opensearch:9200"]
            insecure: true
            username: "admin"
            password: "zmgf-x19a/M12"
      sink:
        - opensearch:
            hosts: ["https://opensearch:9200"]
            index_type: trace-analytics-raw
            insecure: true
            username: "admin"
            password: "zmgf-x19a/M12"

    service-map-pipeline:
      delay: "100"
      source:
        pipeline:
          name: "otel-trace-pipeline"
      processor:
        - service_map_stateful:
      sink:
        - opensearch:
            hosts: ["https://opensearch:9200"]
            index_type: trace-analytics-service-map
            insecure: true
            username: "admin"
            password: "zmgf-x19a/M12"

    log-pipeline:
      source:
        otel_logs_source:
          ssl: false
          port: 21892
      processor:
        - grok:
            match:
              log:
                - "%{SYSLOGTIMESTAMP:timestamp} %{HOSTNAME:hostname} %{PROG:program}\\[%{NUMBER:pid}\\]: %{GREEDYDATA:message}"
      sink:
        - opensearch:
            hosts: [ "https://opensearch:9200" ]
            insecure: true
            username: admin
            password: zmgf-x19a/M12
            index: log-analytics
        - stdout:

    metrics-pipeline:
      source:
        otel_metrics_source:
          ssl: false
          port: 8889
      processor:
        - otel_metrics:
      sink:
        - opensearch:
            hosts: [ "https://opensearch:9200" ]
            insecure: true
            username: admin
            password: zmgf-x19a/M12
            index: metrics-analytics

kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: data-prepper
  name: data-prepper-cm0
