- name: masters install
  hosts: masters
  become: yes
  tasks:

    - name: install overlay network
      become: yes
      become_user: "{{ ansible_user }}"
      ansible.builtin.shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
      run_once: true
      ignore_errors: true

- name: loadbalancers install
  hosts: loadbalancers
  become: yes
  tasks:

    - name: install keepalived
      ansible.builtin.package:
        name: keepalived
        state: latest
      notify: restart keepalived

    - name: check default network interface
      ansible.builtin.debug:
        var: "Interface: {{ ansible_default_ipv4.interface }}"

    - name: keepalived configuration
      ansible.builtin.template:
        src: ./template/keepalived.conf.jinja
        dest: /etc/keepalived/keepalived.conf
      notify: restart keepalived

    - name: start keepalived
      ansible.builtin.service:
        name: keepalived
        state: started
        enabled: yes

    - name: install haproxy
      ansible.builtin.package:
        name: haproxy
        state: latest
      notify: restart haproxy

    - name: keepalived configuration
      ansible.builtin.template:
        src: ./template/haproxy.cfg.jinja
        dest: /etc/haproxy/haproxy.cfg
      notify: restart haproxy

    - name: start haproxy
      ansible.builtin.service:
        name: haproxy
        state: started
        enabled: yes
