masters:
  hosts:
    master1:
      ansible_host: 172.16.16.101
      ansible_user: root
      ansible_password: silentmode
      ansible_become_pass: silentmode

controlplanes:
  hosts:
    master2:
      ansible_host: 172.16.16.102
      ansible_user: root
      ansible_password: silentmode
      ansible_become_pass: silentmode
    master3:
      ansible_host: 172.16.16.103
      ansible_user: root
      ansible_password: silentmode
      ansible_become_pass: silentmode

loadbalancers:
  hosts:
    loadbalancer1:
      ansible_host: 172.16.16.51
      ansible_user: root
      ansible_password: silentmode
      ansible_become_pass: silentmode
    loadbalancer2:
      ansible_host: 172.16.16.52
      ansible_user: root
      ansible_password: silentmode
      ansible_become_pass: silentmode

slaves:
  hosts:
    slave1:
      ansible_host: 172.16.16.201
      ansible_user: root
      ansible_password: silentmode
      ansible_become_pass: silentmode
    slave2:
      ansible_host: 172.16.16.202
      ansible_user: root
      ansible_password: silentmode
      ansible_become_pass: silentmode
    slave3:
      ansible_host: 172.16.16.203
      ansible_user: root
      ansible_password: silentmode
      ansible_become_pass: silentmode


 
 
