networks:
  observer:
    name: observer
    driver: bridge

services:
  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: opentelemetry-collector
    command:
      - --config=/etc/otelcol-contrib/otel-config.yaml
    volumes:
      - ./volume/otel-config.yaml:/etc/otelcol-contrib/otel-config.yaml
    environment:
      - SITE_NAME=${site_name}
      - ROID=${roid}
      - POSTCODE=${postcode}
      - CITY=${city}
      - STATE=${state}
    ports:
      - 4317:4317
      - 8889:8889
    networks:
      - observer

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./volume/prometheus-config.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - observer
