networks:
  observer:
    name: observer
    driver: bridge

services:
  opentelemetry-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: opentelemetry-collector
    command:
      - --config=/etc/otelcol-contrib/otel-config.yaml
    volumes:
      - ./volume/otel-config.yaml:/etc/otelcol-contrib/otel-config.yaml
      - /:/hostfs
    environment:
      - SITE_NAME=${site_name}
      - ROID=${roid}
      - REGION=${region}
      - POSTCODE=${postcode}
      - CITY=${city}
      - STATE=${state}
      - ENVIRONMENT=development
    ports:
      - 4317:4317
      - 8889:8889
    networks:
      - observer

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./volume/prometheus-config.yaml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    networks:
      - observer

  dataprepper:
    image: opensearchproject/data-prepper:latest
    container_name: dataprepper
    volumes:
      - ./volume/pipelines.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml
      - ./volume/data-prepper-config.yaml:/usr/share/data-prepper/config/data-prepper-config.yaml
    ulimits:
      core: -1
    ports:
      - 21891:21891
    networks:
      - observer
