apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opensearch-master
  labels:
    app: opensearch
    role: master
spec:
  replicas: 1
  serviceName: opensearch-master
  selector:
    matchLabels:
      app: opensearch
      role: master
  serviceName: opensearch
  template:
    metadata:
      labels:
        app: opensearch
        role: master
    spec:
      initContainers:
        - name: init-sysctl
          image: busybox:latest
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      containers:
        - name: opensearch-master
          image: opensearchproject/opensearch:2.14.0
          imagePullPolicy: IfNotPresent
          env:
            - name: node.name
              valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
            - name: namespace
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ES_JAVA_OPTS
              value: -Xms512m -Xms512m
            - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
              value: zmgf-x19a/M2
            - name: node.master
              value: "true"
            - name: node.data
              value: "false"
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          volumeMounts:
            - name: opensearch-data
              mountPath: /usr/share/opensearch/data
            - name: opensearch-config
              mountPath: /usr/share/opensearch/config/opensearch.yml
              subPath: opensearch.yml
              readOnly: true
      volumes:
        - name: opensearch-config
          configMap:
            items:
              - key: opensearch.yml
                path: opensearch.yml
            name: opensearch-config
  volumeClaimTemplates:
    - metadata:
        name: opensearch-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
